#!/usr/bin/env node

const sections = [
	['Shared', 'shared_views.js'],
	['List', 'list_views.js'],
	['Edit', 'edit_views.js'],
];

const lines = [
	`// Generated by "generate_views.js", do not edit manually.`,
	'',
	`class CUIViews {`,
	`\tconstructor(/** CUIViews */ source) {`,
];

for (const [title, filename] of sections) {
	lines.push('', '\t\t// ' + title, '');
	const exp = require('../src/views/' + filename);
	for (const name in exp) {
		lines.push(`\t\tthis.${name} = require('../views/${filename}').${name};`);
	}
}

lines.push(
	'',
	`\t\tObject.assign(this, source);`,
	`\t}`,
	`}`,
	'',
	`module.exports = new CUIViews();`,
	`module.exports.CUIViews = CUIViews;`
);

console.log(lines.join('\n'));
