// Generated by "generate_views.js", do not edit manually.

class CBQViews {
	constructor(/** CBQViews */ source) {

		// Shared

		this.layout = require('./shared_views.js').layout;
		this.navigation = require('./shared_views.js').navigation;
		this.header = require('./shared_views.js').header;
		this.footer = require('./shared_views.js').footer;
		this.errorPage = require('./shared_views.js').errorPage;

		// List

		this.listPage = require('./list_views.js').listPage;
		this.listHeader = require('./list_views.js').listHeader;
		this.listAbove = require('./list_views.js').listAbove;
		this.listCreateButton = require('./list_views.js').listCreateButton;
		this.listBelow = require('./list_views.js').listBelow;
		this.listFooter = require('./list_views.js').listFooter;
		this.listContent = require('./list_views.js').listContent;
		this.listColumnHeader = require('./list_views.js').listColumnHeader;
		this.listRow = require('./list_views.js').listRow;
		this.listCell = require('./list_views.js').listCell;
		this.listControlsCell = require('./list_views.js').listControlsCell;
		this.listEditButton = require('./list_views.js').listEditButton;
		this.listDeleteButton = require('./list_views.js').listDeleteButton;
		this.listNoData = require('./list_views.js').listNoData;

		// Edit

		this.editPage = require('./edit_views.js').editPage;
		this.editHeader = require('./edit_views.js').editHeader;
		this.editAbove = require('./edit_views.js').editAbove;
		this.editBelow = require('./edit_views.js').editBelow;
		this.editFooter = require('./edit_views.js').editFooter;
		this.editContent = require('./edit_views.js').editContent;
		this.editField = require('./edit_views.js').editField;
		this.editFieldHelpText = require('./edit_views.js').editFieldHelpText;
		this.editFieldString = require('./edit_views.js').editFieldString;
		this.editFieldText = require('./edit_views.js').editFieldText;
		this.editFieldSelect = require('./edit_views.js').editFieldSelect;

		Object.assign(this, source);
	}
}

module.exports = new CBQViews();
module.exports.CBQViews = CBQViews;
