// Generated by "generate_views.ts", do not edit manually.

import { safeAssign } from '../tools';
import * as Shared from '../views/shared_views';
import * as List from '../views/list_views';
import * as Edit from '../views/edit_views';
import * as Detail from '../views/detail_views';

export class CUIViews {
  // Shared

  public layout = Shared.layout;
  public header = Shared.header;
  public footer = Shared.footer;
  public navigation = Shared.navigation;
  public navigationItem = Shared.navigationItem;
  public navigationDropDownItem = Shared.navigationDropDownItem;
  public flashMessage = Shared.flashMessage;
  public icon = Shared.icon;
  public csrfField = Shared.csrfField;
  public errorPage = Shared.errorPage;

  // List

  public listPage = List.listPage;
  public listHeader = List.listHeader;
  public listAbove = List.listAbove;
  public listCreateButton = List.listCreateButton;
  public listBelow = List.listBelow;
  public listFooter = List.listFooter;
  public listHead = List.listHead;
  public listScripts = List.listScripts;
  public listDeleteModalScripting = List.listDeleteModalScripting;
  public listContent = List.listContent;
  public listColumnHeader = List.listColumnHeader;
  public listRow = List.listRow;
  public listCell = List.listCell;
  public listValue = List.listValue;
  public listControlsCell = List.listControlsCell;
  public listDetailButton = List.listDetailButton;
  public listEditButton = List.listEditButton;
  public listDeleteButton = List.listDeleteButton;
  public listDeleteConfirmationModal = List.listDeleteConfirmationModal;
  public listNoData = List.listNoData;

  // Edit

  public editPage = Edit.editPage;
  public editHeader = Edit.editHeader;
  public editAbove = Edit.editAbove;
  public editBelow = Edit.editBelow;
  public editFooter = Edit.editFooter;
  public editContent = Edit.editContent;
  public editSaveButton = Edit.editSaveButton;
  public editCancelButton = Edit.editCancelButton;
  public editErrorSummary = Edit.editErrorSummary;
  public editField = Edit.editField;
  public editFieldPrepareHelp = Edit.editFieldPrepareHelp;
  public editFieldPrepareError = Edit.editFieldPrepareError;
  public editFieldPrepareValue = Edit.editFieldPrepareValue;
  public editFieldString = Edit.editFieldString;
  public editFieldSecret = Edit.editFieldSecret;
  public editFieldText = Edit.editFieldText;
  public editFieldSelect = Edit.editFieldSelect;
  public editFieldBoolean = Edit.editFieldBoolean;

  // Detail

  public detailPage = Detail.detailPage;
  public detailHeader = Detail.detailHeader;
  public detailAbove = Detail.detailAbove;
  public detailBelow = Detail.detailBelow;
  public detailFooter = Detail.detailFooter;
  public detailHead = Detail.detailHead;
  public detailScripts = Detail.detailScripts;
  public detailContent = Detail.detailContent;
  public detailControls = Detail.detailControls;
  public detailEditButton = Detail.detailEditButton;
  public detailDeleteButton = Detail.detailDeleteButton;
  public detailBackButton = Detail.detailBackButton;
  public detailField = Detail.detailField;
  public detailFieldString = Detail.detailFieldString;
  public detailFieldSecret = Detail.detailFieldSecret;
  public detailFieldText = Detail.detailFieldText;
  public detailFieldSelect = Detail.detailFieldSelect;
  public detailFieldBoolean = Detail.detailFieldBoolean;
  public detailDeleteConfirmationModal = Detail.detailDeleteConfirmationModal;

  constructor(source?: Partial<CUIViews>) {
    safeAssign(this, source);
  }
}

